In [1]:
import math

In [3]:
math.sqrt(25)

5.0

In [4]:
math.pi

3.141592653589793

In [5]:
import math as mt

In [6]:
mt.sqrt(25)

5.0

In [7]:
import math as mt
mt.sqrt(25)

5.0

In [9]:
from numpy import random
import numpy as np

In [11]:
dataOne = random.rand(5,5)
dataOne

array([[0.51153159, 0.20407458, 0.98714305, 0.69772377, 0.12355012],
       [0.44079206, 0.36272305, 0.6412255 , 0.98857465, 0.73536109],
       [0.94835919, 0.30696403, 0.8253064 , 0.50637859, 0.09917748],
       [0.08987639, 0.56035732, 0.00755454, 0.29786557, 0.88049413],
       [0.57742285, 0.00376198, 0.22208571, 0.13687054, 0.8468065 ]])

In [12]:
np.mean(dataOne)

0.4800792272340237

In [14]:
np.sum(dataOne)

12.001980680850592

In [15]:
np.median(dataOne)

0.5063785852378592

In [19]:
np.around(dataOne)

array([[1., 0., 1., 1., 0.],
       [0., 0., 1., 1., 1.],
       [1., 0., 1., 1., 0.],
       [0., 1., 0., 0., 1.],
       [1., 0., 0., 0., 1.]])

In [20]:
np.amin(dataOne)

0.003761975602410983

In [21]:
np.amax(dataOne)

0.9885746481116244

In [24]:
np.average(dataOne)

0.4800792272340237

In [25]:
np.std(dataOne)

0.31740893224921934

In [26]:
print()
print(" I love Data Science")


 I love Data Science


In [27]:
variablename=25
print(variablename)

25


In [28]:
variablename1 = 'I love Data Science'
print(variablename1)

I love Data Science


In [29]:
variablename = 25
type(variablename)

int

In [30]:
type(variablename1)

str

In [32]:
varOne = 25
varTwo = 25.0
varThree = varOne + varTwo
print(varThree)

50.0


In [33]:
varOne = 25
varTwo = 'Hello'
varThree = varOne + varTwo
print(varThree)

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [35]:
varOne = str(25 )
varTwo = 'Hello'
varThree = varOne + varTwo
print(varThree)
print(type(varThree))

25Hello
<class 'str'>


In [39]:
varOne = 25
varTwo = 25.0
varThree = varOne + varTwo
print(varThree)
print(type(varThree))
print(type(varOne))

50.0
<class 'float'>
<class 'int'>


In [45]:
listOne = [1,2,3,4]
print(listOne[0:1])
print(listOne[0:2])
print(listOne[1:3])
print(listOne[0:4])

[1]
[1, 2]
[2, 3]
[1, 2, 3, 4]


In [47]:
tel = {'jack' : 4098, 'sape': 4139}
tel['jack']


4098

In [60]:
# our exercise to print
varDict = {'A':10, 'B':20, 'C':30, 'D':40, 'E':50}
varDict['D']

40

In [55]:
import math as mt
mt.sqrt(varDict['D'])

6.324555320336759

In [56]:
mt.fabs(varDict['B'])

20.0

In [57]:
mt.gcd(varDict['C'],varDict['D'])

10

In [4]:
from scipy import stats as st
from numpy import random
import numpy as np

In [5]:
dataOne = random.rand(5,5)
dataOne

array([[0.34786372, 0.29679792, 0.85224521, 0.8503296 , 0.41832026],
       [0.24519146, 0.03953325, 0.97316143, 0.00482267, 0.73290928],
       [0.27062187, 0.403318  , 0.77869847, 0.40742099, 0.80592058],
       [0.99286215, 0.55149085, 0.70455409, 0.84823993, 0.39672672],
       [0.82468711, 0.1628415 , 0.97127245, 0.5328625 , 0.13206438]])

In [6]:
st.skew(dataOne)

array([ 0.46121624,  0.04130871, -0.13406485, -0.51224522, -0.1039263 ])

In [7]:
st.zscore(dataOne)

array([[-0.60645095,  0.03353285, -0.03536924,  1.0223786 , -0.32170484],
       [-0.93698058, -1.40388232,  1.10779403, -1.66556629,  0.96151308],
       [-0.85511326,  0.62869259, -0.73069302, -0.38566891,  1.25932833],
       [ 1.46997278,  1.45657891, -1.43166699,  1.01573533, -0.40978552],
       [ 0.92857201, -0.71492203,  1.08993521,  0.01312127, -1.48935106]])

In [8]:
st.sem(dataOne)

array([0.15531474, 0.08948864, 0.05288668, 0.15727758, 0.12257817])

In [10]:
st.kurtosis(dataOne)

array([-1.62933567, -1.23937309, -1.5193006 , -1.02503544, -1.33420197])

In [11]:
st.describe(dataOne)

DescribeResult(nobs=5, minmax=(array([0.24519146, 0.03953325, 0.70455409, 0.00482267, 0.13206438]), array([0.99286215, 0.55149085, 0.97316143, 0.8503296 , 0.80592058])), mean=array([0.53624526, 0.2907963 , 0.85598633, 0.52873514, 0.49718824]), variance=array([0.12061335, 0.04004109, 0.01398501, 0.12368119, 0.07512704]), skewness=array([ 0.46121624,  0.04130871, -0.13406485, -0.51224522, -0.1039263 ]), kurtosis=array([-1.62933567, -1.23937309, -1.5193006 , -1.02503544, -1.33420197]))

In [13]:
st.mode(dataOne)

ModeResult(mode=array([[0.24519146, 0.03953325, 0.70455409, 0.00482267, 0.13206438]]), count=array([[1, 1, 1, 1, 1]]))